#!/usr/bin/python
# Copyright (c) 2011 Brian Urrutia <burrutia.biz@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish, dis-
# tribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the fol-
# lowing conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABIL-
# ITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
# SHALL THE AUTHOR BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS

import os, string, ConfigParser, subprocess

config_file = '/etc/datacenter.ini'
config = ConfigParser.ConfigParser()
config.readfp(open(config_file))

basedir = config.get('master-conf', 'basedir')

n = config.get('master-conf', 'host')
u = config.get('master-conf', 'unit')
e = config.get('master-conf', 'env')
c = config.get('master-conf', 'class')
t = config.get('master-conf', 'tld')
d = config.get('master-conf', 'dc')

## change this to arange hostname order
basehost = ("%s%s%s" %(d,e,c))
hostname = ("%s%s"%(basehost,n))
domain = ("%s%s.%s" %(u,e,t))
fqdn = ("%s.%s" %(hostname,domain))

ip = subprocess.Popen( "/usr/bin/facter ipaddress", shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0]

ipaddr = ip.strip("\n")

hosts_file = open('/etc/hosts', "w")
print >> hosts_file, '# autogenerated file, chagnes will be overwritten at boot'
print >> hosts_file, '127.0.0.1  localhost  localhost.localdomain'
print >> hosts_file, '%s %s %s' %(ipaddr, fqdn, hostname)
hosts_file.close()

resolv_conf = open('/etc/resolv.conf', "w")
print >> resolv_conf, 'domain %s' %(domain)
print >> resolv_conf, 'nameserver %s' %(ipaddr)
resolv_conf.close()

master_zone = ("/var/named/zones/master/%s%s.internal.zone.db" %(u,e))
clean_zone = ("/bin/sed -i -e '/^ns1/d' %s" %(master_zone))
subprocess.Popen( clean_zone, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0]

# need to pull out the existing a record for ns1 as do others
fileHandle = open ( master_zone, 'a')
fileHandle.write ( 'ns1\t\tIN\tA\t%s\n' %(ipaddr))
fileHandle.close()

command = ("%s/scripts/set_master_dnsname.py -i %s -H %s" %( basedir, ipaddr, hostname ))
subprocess.Popen( command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0]
subprocess.Popen( "/bin/hostname %s" %(hostname), shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0]
subprocess.Popen( "/bin/domainname %s" %(domain), shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0]
subprocess.Popen( "/etc/init.d/syslog restart", shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0]
named_restart = subprocess.Popen( "/etc/init.d/named restart", shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0]
print named_restart
